# Generated by Django 2.0.2 on 2019-01-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='image/'),
        ),
    ]
