# Generated by Django 2.0.2 on 2019-01-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190111_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='pub_date',
        ),
    ]
